apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-basic
spec:
  rayVersion: '2.47.0'

  headGroupSpec:
    rayStartParams:
      port: '6379'
      num-cpus: '0'

    template:
      spec:
        containers:
        - name: ray-head
          image: ray-dev  # ❗ Skaffold가 빌드한 이미지
          imagePullPolicy: IfNotPresent
          ports:
          - name: gcs-server
            containerPort: 6379
          - name: client
            containerPort: 10001
          - name: dashboard
            containerPort: 8265
          - name: metrics
            containerPort: 8080
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
          - name: ray-logs-hostpath
            mountPath: /tmp/ray
        volumes:
        - name: ray-logs-hostpath
          hostPath:
            path: /var/log/ray_on_host
            type: DirectoryOrCreate

  workerGroupSpecs:
  - groupName: worker-group
    replicas: 4
    minReplicas: 4
    maxReplicas: 4
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: ray-dev  # ❗ Skaffold가 빌드한 이미지
          imagePullPolicy: IfNotPresent
          ports:
          - name: metrics
            containerPort: 8080
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
          volumeMounts:
          - name: ray-logs-hostpath
            mountPath: /tmp/ray
        volumes:
        - name: ray-logs-hostpath
          hostPath:
            path: /var/log/ray_on_host
            type: DirectoryOrCreate
